environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:

    # Python 2.7.10 is the latest version and is not pre-installed.
    - PYTHON: "C:\\Python27.10-x64"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python27.10-x32"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"

    # The lastest Python 3.4.
    - PYTHON: "C:\\Python34-x64" 
      PYTHON_VERSION: "3.4.x" # currently 3.4.3 
      PYTHON_ARCH: "64" 

    - PYTHON: "C:\\Python34-x32" 
      PYTHON_VERSION: "3.4.x" # currently 3.4.3 
      PYTHON_ARCH: "32" 


install:
  # Checking submodule(s) out
  - git submodule update --init --recursive
  # Install miniconda & stdint.h as needed
  - ps: appveyor\install.ps1 -miniconda -stdint 

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process)
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Upgrade to the latest version of conda and install dependencies to build and upload packages
  - conda config --set always_yes yes --set changeps1 no
  # Install the build and test prerequisites
  - conda install -q conda-build anaconda-client
  - conda config --add channels maxirmx

build_script:                                                                                   
  # Check that we have the expected version and architecture for conda
  - conda info -a
  # Build
  - "%CMD_IN_ENV% conda build -q --no-anaconda-upload ."

on_success:
  - "for /f %%f in ('conda build -q --output .') do anaconda -t %ANACONDA_TOKEN% upload -u maxirmx --force --no-progress %%f"

